# Generated by Django 4.0.2 on 2022-02-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
