# Generated by Django 4.0.2 on 2022-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
