# Generated by Django 4.0.2 on 2022-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_todos_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
