# Generated by Django 4.0.2 on 2022-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_todos_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='bookmark',
        ),
        migrations.AddField(
            model_name='todos',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
