# Generated by Django 4.0.2 on 2022-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_todos_bookmark_todos_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
