# Generated by Django 4.0.2 on 2022-02-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_or_bottom',
            field=models.BooleanField(default=False),
        ),
    ]
