# Generated by Django 4.0.2 on 2022-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_add_or_bottom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='move_ticked_item',
            field=models.BooleanField(default=False),
        ),
    ]
