# Generated by Django 4.0.2 on 2022-03-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
